default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_back_end_development
  username: postgres
  password: 1234
  port: 5432
  host: localhost

test:
  <<: *default
  database: hello_rails_back_end_test
  username: postgres
  password: 1234
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
